### ISSUE TITLE
Advancements in perl modules.

### ISSUE THREAD

**Issue by cheako** [grondilu/libbitcoin-perl#1]
Crypt::PK::ECC
Public key cryptography based on EC

Encode::Base58::GMP
High speed Base58 encoding using GMP with BigInt and MD5 support 

These both have Bitcoin support.

I plan on building Finance::Libbitcoin::XS this code would be great as Finance::Libbitcoin::PP!

**Comment by grondilu** [comment]
Hi, libbitcoin-perl is no longer supported nor developed.  I leave it as a public repo in case someone wants to reuse the code.   I guess I should update the README to mention that, though.
