### ISSUE TITLE
Recommend Bitcoin::Crypto?

### ISSUE THREAD

**Issue by bbrtj** [grondilu/libbitcoin-perl#8]
Hello,

Thank you for writing libbitcoin-perl. Would you consider mentioning Bitcoin::Crypto as an alternative in the README? https://metacpan.org/pod/Bitcoin::Crypto

Bitcoin::Crypto is a rich Bitcoin library for Perl which seems to already be doing most of what this library is doing. It's actively developed and has a very robust test suite. It is also available to install from CPAN.

Additionally, if you are still interested in Bitcoin and Perl, feel invited join my Perl Bitcoin Toolchain Collective GitHub organization: https://github.com/Perl-Bitcoin. As you probably know, Bitcoin is a pretty complex topic and there are still tons of features missing from my library which I could use help with. Let me know and I'll send you an invite.

**Comment by grondilu** [comment]
Bitcoin::Crypto now mentioned in the README.

Do you support BIP-0085?

**Comment by bbrtj** [comment]
Thank you. I only learned about BIP85 recently and was planning to implement it, but I'm currently occupied with PSBT support (BIPs 174 and 370). I will most likely implement it after PSBT, as doesn't look like much work to get done.

**Comment by bbrtj** [comment]
@grondilu since you asked, BIP85 is now supported in Bitcoin::Crypto 2.006
